# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('ub_date', models.DateTimeField(verbose_name='date uploaded')),
                ('format', models.CharField(max_length=4)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
